// <auto-generated />
namespace HNGHRMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_pro_employeesalarycomponent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_pro_employeesalarycomponent));
        
        string IMigrationMetadata.Id
        {
            get { return "201604080322354_change_pro_employeesalarycomponent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
