// <auto-generated />
namespace HNGHRMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_empcode_pro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_empcode_pro));
        
        string IMigrationMetadata.Id
        {
            get { return "201604280146456_add_empcode_pro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
