// <auto-generated />
namespace HNGHRMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604200138405_init2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
