// <auto-generated />
namespace HNGHRMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_pro_salary_compoenet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_pro_salary_compoenet));
        
        string IMigrationMetadata.Id
        {
            get { return "201604110143262_add_pro_salary_compoenet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
